import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>hihihi</div>
        <ul>
          <li>gigi</li>
        </ul>
      </main>

      <footer></footer>
    </div>
  );
}
